-- convert blanks to NULLs
update load_next_msl_33 set srcHigherTaxon=null where srcHigherTaxon=''
update load_next_msl_33 set srcOrder=null where srcOrder=''
update load_next_msl_33 set srcFamily=null where srcFamily=''
update load_next_msl_33 set srcSubfamily=null where srcSubfamily=''
update load_next_msl_33 set srcGenus=null where srcGenus=''
update load_next_msl_33 set srcSpecies=null where srcSpecies=''
update load_next_msl_33 set srcistype=null where srcistype=''

update load_next_msl_33 set srcAccessions=null where srcAccessions=''
update load_next_msl_33 set subphylum=null where subphylum=''
update load_next_msl_33 set [class]=null where [class]=''

update load_next_msl_33 set subclass=null where subclass=''
update load_next_msl_33 set [order]=null where [order]=''
update load_next_msl_33 set suborder=null where suborder=''
update load_next_msl_33 set family=null where family=''
update load_next_msl_33 set subfamily=null where subfamily=''
update load_next_msl_33 set genus=null where genus=''
update load_next_msl_33 set subgenus=null where subgenus=''
update load_next_msl_33 set species=null where species=''
update load_next_msl_33 set isType=null where isType=''
update load_next_msl_33 set accessions=null where accessions=''
update load_next_msl_33 set exemplarName=null where exemplarName=''
update load_next_msl_33 set exemplarID=null where exemplarID=''
update load_next_msl_33 set isComplete=null where isComplete=''
update load_next_msl_33 set Abbrev=null where Abbrev=''
update load_next_msl_33 set change=null where change=''