-- convert blanks to NULLs
-- !! this is necessary when loading from .txt files, but not when loading from .xls !!
update load_next_msl set [sort]=null where [sort]=''



update load_next_msl set [proposal]=NULL where [proposal]='' 
update load_next_msl set [proposal_abbrev]=NULL where [proposal_abbrev]='' 
update load_next_msl set [srcRealm]=NULL where [srcRealm]='' 
update load_next_msl set [srcSubrealm]=NULL where [srcSubrealm]='' 
update load_next_msl set [srcKingdom]=NULL where [srcKingdom]='' 
update load_next_msl set [srcSubkingdom]=NULL where [srcSubkingdom]='' 
update load_next_msl set [srcPhylum]=NULL where [srcPhylum]='' 
update load_next_msl set [srcSubphylum]=NULL where [srcSubphylum]='' 
update load_next_msl set [srcClass]=NULL where [srcClass]='' 
update load_next_msl set [srcSubclass]=NULL where [srcSubclass]='' 
update load_next_msl set [srcOrder]=NULL where [srcOrder]='' 
update load_next_msl set [srcSuborder]=NULL where [srcSuborder]='' 
update load_next_msl set [srcFamily]=NULL where [srcFamily]='' 
update load_next_msl set [srcSubfamily]=NULL where [srcSubfamily]='' 
update load_next_msl set [srcGenus]=NULL where [srcGenus]='' 
update load_next_msl set [srcSubgenus]=NULL where [srcSubgenus]='' 
update load_next_msl set [srcSpecies]=NULL where [srcSpecies]='' 
update load_next_msl set [realm]=NULL where [realm]='' 
update load_next_msl set [subrealm]=NULL where [subrealm]='' 
update load_next_msl set [kingdom]=NULL where [kingdom]='' 
update load_next_msl set [subkingdom]=NULL where [subkingdom]='' 
update load_next_msl set [phylum]=NULL where [phylum]='' 
update load_next_msl set [subphylum]=NULL where [subphylum]='' 
update load_next_msl set [class]=NULL where [class]='' 
update load_next_msl set [subclass]=NULL where [subclass]='' 
update load_next_msl set [order]=NULL where [order]='' 
update load_next_msl set [suborder]=NULL where [suborder]='' 
update load_next_msl set [family]=NULL where [family]='' 
update load_next_msl set [subfamily]=NULL where [subfamily]='' 
update load_next_msl set [genus]=NULL where [genus]='' 
update load_next_msl set [subgenus]=NULL where [subgenus]='' 
update load_next_msl set [species]=NULL where [species]='' 
update load_next_msl set [isType]=NULL where [isType]='' 
update load_next_msl set [exemplarAccessions]=NULL where [exemplarAccessions]='' 
update load_next_msl set [exemplarName]=NULL where [exemplarName]='' 
update load_next_msl set [exemplarRefSeq]=NULL where [exemplarRefSeq]='' 
update load_next_msl set [exemplarIsolate]=NULL where [exemplarIsolate]='' 
update load_next_msl set [isComplete]=NULL where [isComplete]='' 
update load_next_msl set [Abbrev]=NULL where [Abbrev]='' 
update load_next_msl set [change]=NULL where [change]='' 
update load_next_msl set [rank]=NULL where [rank]='' 
