--
-- data cleaning of load_next_msl
--
-- UPDATE FOR NEW TAXON LEVELS
--
-- NOTE: [SQL code generated by sibling XLSX file.]
--
-- 1. remove tab, nb-space, multiple whitespace and leading/trailing whitespace
-- 2. microsoft curvey quotees => ascii quotes
-- 3. things in quotes, remove quotes
-- 4. proposal filename suffix fixing
--
-- CHANGE LOG
-- MSL35 - added removable of non-breaking spaces char(160)
--------------------------------------------------------------------------------
begin transaction
-- COMMIT TRANSACTION

print '-- remove leading and trailing spaces (update create in excel)'
update load_next_msl set
--select [change],[exemplarAccessions],
      [proposal]=rtrim(ltrim(replace(replace(replace([proposal],char(9),' '),char(160),' '),'  ',' ')))
      ,[srcRealm]=rtrim(ltrim(replace(replace(replace([srcRealm],char(9),' '),char(160),' '),'  ',' ')))
      ,[srcSubrealm]=rtrim(ltrim(replace(replace(replace([srcSubrealm],char(9),' '),char(160),' '),'  ',' ')))
      ,[srcKingdom]=rtrim(ltrim(replace(replace(replace([srcKingdom],char(9),' '),char(160),' '),'  ',' ')))
      ,[srcSubkingdom]=rtrim(ltrim(replace(replace(replace([srcSubkingdom],char(9),' '),char(160),' '),'  ',' ')))
      ,[srcPhylum]=rtrim(ltrim(replace(replace(replace([srcPhylum],char(9),' '),char(160),' '),'  ',' ')))
      ,[srcSubphylum]=rtrim(ltrim(replace(replace(replace([srcSubphylum],char(9),' '),char(160),' '),'  ',' ')))
      ,[srcClass]=rtrim(ltrim(replace(replace(replace([srcClass],char(9),' '),char(160),' '),'  ',' ')))
      ,[srcSubclass]=rtrim(ltrim(replace(replace(replace([srcSubclass],char(9),' '),char(160),' '),'  ',' ')))
      ,[srcOrder]=rtrim(ltrim(replace(replace(replace([srcOrder],char(9),' '),char(160),' '),'  ',' ')))
      ,[srcSuborder]=rtrim(ltrim(replace(replace(replace([srcSuborder],char(9),' '),char(160),' '),'  ',' ')))
      ,[srcFamily]=rtrim(ltrim(replace(replace(replace([srcFamily],char(9),' '),char(160),' '),'  ',' ')))
      ,[srcSubfamily]=rtrim(ltrim(replace(replace(replace([srcSubfamily],char(9),' '),char(160),' '),'  ',' ')))
      ,[srcGenus]=rtrim(ltrim(replace(replace(replace([srcGenus],char(9),' '),char(160),' '),'  ',' ')))
      ,[srcSubgenus]=rtrim(ltrim(replace(replace(replace([srcSubgenus],char(9),' '),char(160),' '),'  ',' ')))
      ,[srcSpecies]=rtrim(ltrim(replace(replace(replace([srcSpecies],char(9),' '),char(160),' '),'  ',' ')))
      ,[srcIsType]=rtrim(ltrim(replace(replace(replace([srcIsType],char(9),' '),char(160),' '),'  ',' ')))
      ,[srcAccessions]=rtrim(ltrim(replace(replace(replace([srcAccessions],char(9),' '),char(160),' '),'  ',' ')))
      ,[realm]=rtrim(ltrim(replace(replace(replace([realm],char(9),' '),char(160),' '),'  ',' ')))
      ,[subrealm]=rtrim(ltrim(replace(replace(replace([subrealm],char(9),' '),char(160),' '),'  ',' ')))
      ,[kingdom]=rtrim(ltrim(replace(replace(replace([kingdom],char(9),' '),char(160),' '),'  ',' ')))
      ,[subkingdom]=rtrim(ltrim(replace(replace(replace([subkingdom],char(9),' '),char(160),' '),'  ',' ')))
      ,[phylum]=rtrim(ltrim(replace(replace(replace([phylum],char(9),' '),char(160),' '),'  ',' ')))
      ,[subphylum]=rtrim(ltrim(replace(replace(replace([subphylum],char(9),' '),char(160),' '),'  ',' ')))
      ,[class]=rtrim(ltrim(replace(replace(replace([class],char(9),' '),char(160),' '),'  ',' ')))
      ,[subclass]=rtrim(ltrim(replace(replace(replace([subclass],char(9),' '),char(160),' '),'  ',' ')))
      ,[order]=rtrim(ltrim(replace(replace(replace([order],char(9),' '),char(160),' '),'  ',' ')))
      ,[suborder]=rtrim(ltrim(replace(replace(replace([suborder],char(9),' '),char(160),' '),'  ',' ')))
      ,[family]=rtrim(ltrim(replace(replace(replace([family],char(9),' '),char(160),' '),'  ',' ')))
      ,[subfamily]=rtrim(ltrim(replace(replace(replace([subfamily],char(9),' '),char(160),' '),'  ',' ')))
      ,[genus]=rtrim(ltrim(replace(replace(replace([genus],char(9),' '),char(160),' '),'  ',' ')))
      ,[subgenus]=rtrim(ltrim(replace(replace(replace([subgenus],char(9),' '),char(160),' '),'  ',' ')))
      ,[species]=rtrim(ltrim(replace(replace(replace([species],char(9),' '),char(160),' '),'  ',' ')))
      ,[isType]=rtrim(ltrim(replace(replace(replace([isType],char(9),' '),char(160),' '),'  ',' ')))
      ,[exemplarAccessions]=rtrim(ltrim(replace(replace(replace([exemplarAccessions],char(9),' '),char(160),' '),'  ',' ')))
      ,[exemplarName]=rtrim(ltrim(replace(replace(replace([exemplarName],char(9),' '),char(160),' '),'  ',' ')))
      ,[exemplarRefSeq]=rtrim(ltrim(replace(replace(replace([exemplarRefSeq],char(9),' '),char(160),' '),'  ',' ')))
      ,[exemplarIsolate]=rtrim(ltrim(replace(replace(replace([exemplarIsolate],char(9),' '),char(160),' '),'  ',' ')))
      ,[isComplete]=rtrim(ltrim(replace(replace(replace([isComplete],char(9),' '),char(160),' '),'  ',' ')))
      ,[Abbrev]=rtrim(ltrim(replace(replace(replace([Abbrev],char(9),' '),char(160),' '),'  ',' ')))
      ,[change]=rtrim(ltrim(replace(replace(replace([change],char(9),' '),char(160),' '),'  ',' ')))
      ,[rank]=rtrim(ltrim(replace(replace(replace([rank],char(9),' '),char(160),' '),'  ',' ')))
from load_next_msl
where
([proposal] is not null and ([proposal] like ' %' or [proposal] like '% ' or [proposal] like '%'+char(9)+'%' or [proposal] like '%'+char(160)+'%' or [proposal] like '%  %')) or  
([srcRealm] is not null and ([srcRealm] like ' %' or [srcRealm] like '% ' or [srcRealm] like '%'+char(9)+'%' or [srcRealm] like '%'+char(160)+'%' or [srcRealm] like '%  %')) or  
([srcSubrealm] is not null and ([srcSubrealm] like ' %' or [srcSubrealm] like '% ' or [srcSubrealm] like '%'+char(9)+'%' or [srcSubrealm] like '%'+char(160)+'%' or [srcSubrealm] like '%  %')) or  
([srcKingdom] is not null and ([srcKingdom] like ' %' or [srcKingdom] like '% ' or [srcKingdom] like '%'+char(9)+'%' or [srcKingdom] like '%'+char(160)+'%' or [srcKingdom] like '%  %')) or  
([srcSubkingdom] is not null and ([srcSubkingdom] like ' %' or [srcSubkingdom] like '% ' or [srcSubkingdom] like '%'+char(9)+'%' or [srcSubkingdom] like '%'+char(160)+'%' or [srcSubkingdom] like '%  %')) or  
([srcPhylum] is not null and ([srcPhylum] like ' %' or [srcPhylum] like '% ' or [srcPhylum] like '%'+char(9)+'%' or [srcPhylum] like '%'+char(160)+'%' or [srcPhylum] like '%  %')) or  
([srcSubphylum] is not null and ([srcSubphylum] like ' %' or [srcSubphylum] like '% ' or [srcSubphylum] like '%'+char(9)+'%' or [srcSubphylum] like '%'+char(160)+'%' or [srcSubphylum] like '%  %')) or  
([srcClass] is not null and ([srcClass] like ' %' or [srcClass] like '% ' or [srcClass] like '%'+char(9)+'%' or [srcClass] like '%'+char(160)+'%' or [srcClass] like '%  %')) or  
([srcSubclass] is not null and ([srcSubclass] like ' %' or [srcSubclass] like '% ' or [srcSubclass] like '%'+char(9)+'%' or [srcSubclass] like '%'+char(160)+'%' or [srcSubclass] like '%  %')) or  
([srcOrder] is not null and ([srcOrder] like ' %' or [srcOrder] like '% ' or [srcOrder] like '%'+char(9)+'%' or [srcOrder] like '%'+char(160)+'%' or [srcOrder] like '%  %')) or  
([srcSuborder] is not null and ([srcSuborder] like ' %' or [srcSuborder] like '% ' or [srcSuborder] like '%'+char(9)+'%' or [srcSuborder] like '%'+char(160)+'%' or [srcSuborder] like '%  %')) or  
([srcFamily] is not null and ([srcFamily] like ' %' or [srcFamily] like '% ' or [srcFamily] like '%'+char(9)+'%' or [srcFamily] like '%'+char(160)+'%' or [srcFamily] like '%  %')) or  
([srcSubfamily] is not null and ([srcSubfamily] like ' %' or [srcSubfamily] like '% ' or [srcSubfamily] like '%'+char(9)+'%' or [srcSubfamily] like '%'+char(160)+'%' or [srcSubfamily] like '%  %')) or  
([srcGenus] is not null and ([srcGenus] like ' %' or [srcGenus] like '% ' or [srcGenus] like '%'+char(9)+'%' or [srcGenus] like '%'+char(160)+'%' or [srcGenus] like '%  %')) or  
([srcSubgenus] is not null and ([srcSubgenus] like ' %' or [srcSubgenus] like '% ' or [srcSubgenus] like '%'+char(9)+'%' or [srcSubgenus] like '%'+char(160)+'%' or [srcSubgenus] like '%  %')) or  
([srcSpecies] is not null and ([srcSpecies] like ' %' or [srcSpecies] like '% ' or [srcSpecies] like '%'+char(9)+'%' or [srcSpecies] like '%'+char(160)+'%' or [srcSpecies] like '%  %')) or  
([srcIsType] is not null and ([srcIsType] like ' %' or [srcIsType] like '% ' or [srcIsType] like '%'+char(9)+'%' or [srcIsType] like '%'+char(160)+'%' or [srcIsType] like '%  %')) or  
([srcAccessions] is not null and ([srcAccessions] like ' %' or [srcAccessions] like '% ' or [srcAccessions] like '%'+char(9)+'%' or [srcAccessions] like '%'+char(160)+'%' or [srcAccessions] like '%  %')) or  
([realm] is not null and ([realm] like ' %' or [realm] like '% ' or [realm] like '%'+char(9)+'%' or [realm] like '%'+char(160)+'%' or [realm] like '%  %')) or  
([subrealm] is not null and ([subrealm] like ' %' or [subrealm] like '% ' or [subrealm] like '%'+char(9)+'%' or [subrealm] like '%'+char(160)+'%' or [subrealm] like '%  %')) or  
([kingdom] is not null and ([kingdom] like ' %' or [kingdom] like '% ' or [kingdom] like '%'+char(9)+'%' or [kingdom] like '%'+char(160)+'%' or [kingdom] like '%  %')) or  
([subkingdom] is not null and ([subkingdom] like ' %' or [subkingdom] like '% ' or [subkingdom] like '%'+char(9)+'%' or [subkingdom] like '%'+char(160)+'%' or [subkingdom] like '%  %')) or  
([phylum] is not null and ([phylum] like ' %' or [phylum] like '% ' or [phylum] like '%'+char(9)+'%' or [phylum] like '%'+char(160)+'%' or [phylum] like '%  %')) or  
([subphylum] is not null and ([subphylum] like ' %' or [subphylum] like '% ' or [subphylum] like '%'+char(9)+'%' or [subphylum] like '%'+char(160)+'%' or [subphylum] like '%  %')) or  
([class] is not null and ([class] like ' %' or [class] like '% ' or [class] like '%'+char(9)+'%' or [class] like '%'+char(160)+'%' or [class] like '%  %')) or  
([subclass] is not null and ([subclass] like ' %' or [subclass] like '% ' or [subclass] like '%'+char(9)+'%' or [subclass] like '%'+char(160)+'%' or [subclass] like '%  %')) or  
([order] is not null and ([order] like ' %' or [order] like '% ' or [order] like '%'+char(9)+'%' or [order] like '%'+char(160)+'%' or [order] like '%  %')) or  
([suborder] is not null and ([suborder] like ' %' or [suborder] like '% ' or [suborder] like '%'+char(9)+'%' or [suborder] like '%'+char(160)+'%' or [suborder] like '%  %')) or  
([family] is not null and ([family] like ' %' or [family] like '% ' or [family] like '%'+char(9)+'%' or [family] like '%'+char(160)+'%' or [family] like '%  %')) or  
([subfamily] is not null and ([subfamily] like ' %' or [subfamily] like '% ' or [subfamily] like '%'+char(9)+'%' or [subfamily] like '%'+char(160)+'%' or [subfamily] like '%  %')) or  
([genus] is not null and ([genus] like ' %' or [genus] like '% ' or [genus] like '%'+char(9)+'%' or [genus] like '%'+char(160)+'%' or [genus] like '%  %')) or  
([subgenus] is not null and ([subgenus] like ' %' or [subgenus] like '% ' or [subgenus] like '%'+char(9)+'%' or [subgenus] like '%'+char(160)+'%' or [subgenus] like '%  %')) or  
([species] is not null and ([species] like ' %' or [species] like '% ' or [species] like '%'+char(9)+'%' or [species] like '%'+char(160)+'%' or [species] like '%  %')) or  
([isType] is not null and ([isType] like ' %' or [isType] like '% ' or [isType] like '%'+char(9)+'%' or [isType] like '%'+char(160)+'%' or [isType] like '%  %')) or  
([exemplarAccessions] is not null and ([exemplarAccessions] like ' %' or [exemplarAccessions] like '% ' or [exemplarAccessions] like '%'+char(9)+'%' or [exemplarAccessions] like '%'+char(160)+'%' or [exemplarAccessions] like '%  %')) or  
([exemplarName] is not null and ([exemplarName] like ' %' or [exemplarName] like '% ' or [exemplarName] like '%'+char(9)+'%' or [exemplarName] like '%'+char(160)+'%' or [exemplarName] like '%  %')) or  
([exemplarRefSeq] is not null and ([exemplarRefSeq] like ' %' or [exemplarRefSeq] like '% ' or [exemplarRefSeq] like '%'+char(9)+'%' or [exemplarRefSeq] like '%'+char(160)+'%' or [exemplarRefSeq] like '%  %')) or  
([exemplarIsolate] is not null and ([exemplarIsolate] like ' %' or [exemplarIsolate] like '% ' or [exemplarIsolate] like '%'+char(9)+'%' or [exemplarIsolate] like '%'+char(160)+'%' or [exemplarIsolate] like '%  %')) or  
([isComplete] is not null and ([isComplete] like ' %' or [isComplete] like '% ' or [isComplete] like '%'+char(9)+'%' or [isComplete] like '%'+char(160)+'%' or [isComplete] like '%  %')) or  
([Abbrev] is not null and ([Abbrev] like ' %' or [Abbrev] like '% ' or [Abbrev] like '%'+char(9)+'%' or [Abbrev] like '%'+char(160)+'%' or [Abbrev] like '%  %')) or  
([change] is not null and ([change] like ' %' or [change] like '% ' or [change] like '%'+char(9)+'%' or [change] like '%'+char(160)+'%' or [change] like '%  %')) or  
([rank] is not null and ([rank] like ' %' or [rank] like '% ' or [rank] like '%'+char(9)+'%' or [rank] like '%'+char(160)+'%' or [rank] like '%  %')) 



print '-- map word smart quotes to regular quotes'
print '--   open smart quote ('+char(147)+') = '+rtrim(ascii('“'))
print '--   close smart quote ('+char(148)+') = '+rtrim(ascii('”'))
print '--   ASCII quote ('+char(34)+') = '+rtrim(ascii('"'))

update load_next_msl set
--select 
      [proposal]=replace(replace([proposal],char(147),char(34)),char(148),char(34))
      ,[srcRealm]=replace(replace([srcRealm],char(147),char(34)),char(148),char(34))
      ,[srcSubrealm]=replace(replace([srcSubrealm],char(147),char(34)),char(148),char(34))
      ,[srcKingdom]=replace(replace([srcKingdom],char(147),char(34)),char(148),char(34))
      ,[srcSubkingdom]=replace(replace([srcSubkingdom],char(147),char(34)),char(148),char(34))
      ,[srcPhylum]=replace(replace([srcPhylum],char(147),char(34)),char(148),char(34))
      ,[srcSubphylum]=replace(replace([srcSubphylum],char(147),char(34)),char(148),char(34))
      ,[srcClass]=replace(replace([srcClass],char(147),char(34)),char(148),char(34))
      ,[srcSubclass]=replace(replace([srcSubclass],char(147),char(34)),char(148),char(34))
      ,[srcOrder]=replace(replace([srcOrder],char(147),char(34)),char(148),char(34))
      ,[srcSuborder]=replace(replace([srcSuborder],char(147),char(34)),char(148),char(34))
      ,[srcFamily]=replace(replace([srcFamily],char(147),char(34)),char(148),char(34))
      ,[srcSubfamily]=replace(replace([srcSubfamily],char(147),char(34)),char(148),char(34))
      ,[srcGenus]=replace(replace([srcGenus],char(147),char(34)),char(148),char(34))
      ,[srcSubgenus]=replace(replace([srcSubgenus],char(147),char(34)),char(148),char(34))
      ,[srcSpecies]=replace(replace([srcSpecies],char(147),char(34)),char(148),char(34))
      ,[srcIsType]=replace(replace([srcIsType],char(147),char(34)),char(148),char(34))
      ,[srcAccessions]=replace(replace([srcAccessions],char(147),char(34)),char(148),char(34))
      ,[realm]=replace(replace([realm],char(147),char(34)),char(148),char(34))
      ,[subrealm]=replace(replace([subrealm],char(147),char(34)),char(148),char(34))
      ,[kingdom]=replace(replace([kingdom],char(147),char(34)),char(148),char(34))
      ,[subkingdom]=replace(replace([subkingdom],char(147),char(34)),char(148),char(34))
      ,[phylum]=replace(replace([phylum],char(147),char(34)),char(148),char(34))
      ,[subphylum]=replace(replace([subphylum],char(147),char(34)),char(148),char(34))
      ,[class]=replace(replace([class],char(147),char(34)),char(148),char(34))
      ,[subclass]=replace(replace([subclass],char(147),char(34)),char(148),char(34))
      ,[order]=replace(replace([order],char(147),char(34)),char(148),char(34))
      ,[suborder]=replace(replace([suborder],char(147),char(34)),char(148),char(34))
      ,[family]=replace(replace([family],char(147),char(34)),char(148),char(34))
      ,[subfamily]=replace(replace([subfamily],char(147),char(34)),char(148),char(34))
      ,[genus]=replace(replace([genus],char(147),char(34)),char(148),char(34))
      ,[subgenus]=replace(replace([subgenus],char(147),char(34)),char(148),char(34))
      ,[species]=replace(replace([species],char(147),char(34)),char(148),char(34))
      ,[isType]=replace(replace([isType],char(147),char(34)),char(148),char(34))
      ,[exemplarAccessions]=replace(replace([exemplarAccessions],char(147),char(34)),char(148),char(34))
      ,[exemplarName]=replace(replace([exemplarName],char(147),char(34)),char(148),char(34))
      ,[exemplarRefSeq]=replace(replace([exemplarRefSeq],char(147),char(34)),char(148),char(34))
      ,[exemplarIsolate]=replace(replace([exemplarIsolate],char(147),char(34)),char(148),char(34))
      ,[isComplete]=replace(replace([isComplete],char(147),char(34)),char(148),char(34))
      ,[Abbrev]=replace(replace([Abbrev],char(147),char(34)),char(148),char(34))
      ,[change]=replace(replace([change],char(147),char(34)),char(148),char(34))
      ,[rank]=replace(replace([rank],char(147),char(34)),char(148),char(34))
from load_next_msl
where
([proposal] is not null and ([proposal] like '%'+char(147)+'%' or [proposal] like '%'+char(148)+'%')) or  -- word smart quotes
([srcRealm] is not null and ([srcRealm] like '%'+char(147)+'%' or [srcRealm] like '%'+char(148)+'%')) or  -- word smart quotes
([srcSubrealm] is not null and ([srcSubrealm] like '%'+char(147)+'%' or [srcSubrealm] like '%'+char(148)+'%')) or  -- word smart quotes
([srcKingdom] is not null and ([srcKingdom] like '%'+char(147)+'%' or [srcKingdom] like '%'+char(148)+'%')) or  -- word smart quotes
([srcSubkingdom] is not null and ([srcSubkingdom] like '%'+char(147)+'%' or [srcSubkingdom] like '%'+char(148)+'%')) or  -- word smart quotes
([srcPhylum] is not null and ([srcPhylum] like '%'+char(147)+'%' or [srcPhylum] like '%'+char(148)+'%')) or  -- word smart quotes
([srcSubphylum] is not null and ([srcSubphylum] like '%'+char(147)+'%' or [srcSubphylum] like '%'+char(148)+'%')) or  -- word smart quotes
([srcClass] is not null and ([srcClass] like '%'+char(147)+'%' or [srcClass] like '%'+char(148)+'%')) or  -- word smart quotes
([srcSubclass] is not null and ([srcSubclass] like '%'+char(147)+'%' or [srcSubclass] like '%'+char(148)+'%')) or  -- word smart quotes
([srcOrder] is not null and ([srcOrder] like '%'+char(147)+'%' or [srcOrder] like '%'+char(148)+'%')) or  -- word smart quotes
([srcSuborder] is not null and ([srcSuborder] like '%'+char(147)+'%' or [srcSuborder] like '%'+char(148)+'%')) or  -- word smart quotes
([srcFamily] is not null and ([srcFamily] like '%'+char(147)+'%' or [srcFamily] like '%'+char(148)+'%')) or  -- word smart quotes
([srcSubfamily] is not null and ([srcSubfamily] like '%'+char(147)+'%' or [srcSubfamily] like '%'+char(148)+'%')) or  -- word smart quotes
([srcGenus] is not null and ([srcGenus] like '%'+char(147)+'%' or [srcGenus] like '%'+char(148)+'%')) or  -- word smart quotes
([srcSubgenus] is not null and ([srcSubgenus] like '%'+char(147)+'%' or [srcSubgenus] like '%'+char(148)+'%')) or  -- word smart quotes
([srcSpecies] is not null and ([srcSpecies] like '%'+char(147)+'%' or [srcSpecies] like '%'+char(148)+'%')) or  -- word smart quotes
([srcIsType] is not null and ([srcIsType] like '%'+char(147)+'%' or [srcIsType] like '%'+char(148)+'%')) or  -- word smart quotes
([srcAccessions] is not null and ([srcAccessions] like '%'+char(147)+'%' or [srcAccessions] like '%'+char(148)+'%')) or  -- word smart quotes
([realm] is not null and ([realm] like '%'+char(147)+'%' or [realm] like '%'+char(148)+'%')) or  -- word smart quotes
([subrealm] is not null and ([subrealm] like '%'+char(147)+'%' or [subrealm] like '%'+char(148)+'%')) or  -- word smart quotes
([kingdom] is not null and ([kingdom] like '%'+char(147)+'%' or [kingdom] like '%'+char(148)+'%')) or  -- word smart quotes
([subkingdom] is not null and ([subkingdom] like '%'+char(147)+'%' or [subkingdom] like '%'+char(148)+'%')) or  -- word smart quotes
([phylum] is not null and ([phylum] like '%'+char(147)+'%' or [phylum] like '%'+char(148)+'%')) or  -- word smart quotes
([subphylum] is not null and ([subphylum] like '%'+char(147)+'%' or [subphylum] like '%'+char(148)+'%')) or  -- word smart quotes
([class] is not null and ([class] like '%'+char(147)+'%' or [class] like '%'+char(148)+'%')) or  -- word smart quotes
([subclass] is not null and ([subclass] like '%'+char(147)+'%' or [subclass] like '%'+char(148)+'%')) or  -- word smart quotes
([order] is not null and ([order] like '%'+char(147)+'%' or [order] like '%'+char(148)+'%')) or  -- word smart quotes
([suborder] is not null and ([suborder] like '%'+char(147)+'%' or [suborder] like '%'+char(148)+'%')) or  -- word smart quotes
([family] is not null and ([family] like '%'+char(147)+'%' or [family] like '%'+char(148)+'%')) or  -- word smart quotes
([subfamily] is not null and ([subfamily] like '%'+char(147)+'%' or [subfamily] like '%'+char(148)+'%')) or  -- word smart quotes
([genus] is not null and ([genus] like '%'+char(147)+'%' or [genus] like '%'+char(148)+'%')) or  -- word smart quotes
([subgenus] is not null and ([subgenus] like '%'+char(147)+'%' or [subgenus] like '%'+char(148)+'%')) or  -- word smart quotes
([species] is not null and ([species] like '%'+char(147)+'%' or [species] like '%'+char(148)+'%')) or  -- word smart quotes
([isType] is not null and ([isType] like '%'+char(147)+'%' or [isType] like '%'+char(148)+'%')) or  -- word smart quotes
([exemplarAccessions] is not null and ([exemplarAccessions] like '%'+char(147)+'%' or [exemplarAccessions] like '%'+char(148)+'%')) or  -- word smart quotes
([exemplarName] is not null and ([exemplarName] like '%'+char(147)+'%' or [exemplarName] like '%'+char(148)+'%')) or  -- word smart quotes
([exemplarRefSeq] is not null and ([exemplarRefSeq] like '%'+char(147)+'%' or [exemplarRefSeq] like '%'+char(148)+'%')) or  -- word smart quotes
([exemplarIsolate] is not null and ([exemplarIsolate] like '%'+char(147)+'%' or [exemplarIsolate] like '%'+char(148)+'%')) or  -- word smart quotes
([isComplete] is not null and ([isComplete] like '%'+char(147)+'%' or [isComplete] like '%'+char(148)+'%')) or  -- word smart quotes
([Abbrev] is not null and ([Abbrev] like '%'+char(147)+'%' or [Abbrev] like '%'+char(148)+'%')) or  -- word smart quotes
([change] is not null and ([change] like '%'+char(147)+'%' or [change] like '%'+char(148)+'%')) or  -- word smart quotes
([rank] is not null and ([rank] like '%'+char(147)+'%' or [rank] like '%'+char(148)+'%'))   -- word smart quotes



print '-- remove quotes around values'
update load_next_msl set 
-- select change,[srcAccessions],[exemplarAccessions],
      [proposal]=(case when [proposal] like char(34)+'%'+char(34) then substring([proposal], 2, len([proposal])-2) else [proposal] end)
      ,[srcRealm]=(case when [srcRealm] like char(34)+'%'+char(34) then substring([srcRealm], 2, len([srcRealm])-2) else [srcRealm] end)
      ,[srcSubrealm]=(case when [srcSubrealm] like char(34)+'%'+char(34) then substring([srcSubrealm], 2, len([srcSubrealm])-2) else [srcSubrealm] end)
      ,[srcKingdom]=(case when [srcKingdom] like char(34)+'%'+char(34) then substring([srcKingdom], 2, len([srcKingdom])-2) else [srcKingdom] end)
      ,[srcSubkingdom]=(case when [srcSubkingdom] like char(34)+'%'+char(34) then substring([srcSubkingdom], 2, len([srcSubkingdom])-2) else [srcSubkingdom] end)
      ,[srcPhylum]=(case when [srcPhylum] like char(34)+'%'+char(34) then substring([srcPhylum], 2, len([srcPhylum])-2) else [srcPhylum] end)
      ,[srcSubphylum]=(case when [srcSubphylum] like char(34)+'%'+char(34) then substring([srcSubphylum], 2, len([srcSubphylum])-2) else [srcSubphylum] end)
      ,[srcClass]=(case when [srcClass] like char(34)+'%'+char(34) then substring([srcClass], 2, len([srcClass])-2) else [srcClass] end)
      ,[srcSubclass]=(case when [srcSubclass] like char(34)+'%'+char(34) then substring([srcSubclass], 2, len([srcSubclass])-2) else [srcSubclass] end)
      ,[srcOrder]=(case when [srcOrder] like char(34)+'%'+char(34) then substring([srcOrder], 2, len([srcOrder])-2) else [srcOrder] end)
      ,[srcSuborder]=(case when [srcSuborder] like char(34)+'%'+char(34) then substring([srcSuborder], 2, len([srcSuborder])-2) else [srcSuborder] end)
      ,[srcFamily]=(case when [srcFamily] like char(34)+'%'+char(34) then substring([srcFamily], 2, len([srcFamily])-2) else [srcFamily] end)
      ,[srcSubfamily]=(case when [srcSubfamily] like char(34)+'%'+char(34) then substring([srcSubfamily], 2, len([srcSubfamily])-2) else [srcSubfamily] end)
      ,[srcGenus]=(case when [srcGenus] like char(34)+'%'+char(34) then substring([srcGenus], 2, len([srcGenus])-2) else [srcGenus] end)
      ,[srcSubgenus]=(case when [srcSubgenus] like char(34)+'%'+char(34) then substring([srcSubgenus], 2, len([srcSubgenus])-2) else [srcSubgenus] end)
      ,[srcSpecies]=(case when [srcSpecies] like char(34)+'%'+char(34) then substring([srcSpecies], 2, len([srcSpecies])-2) else [srcSpecies] end)
      ,[srcIsType]=(case when [srcIsType] like char(34)+'%'+char(34) then substring([srcIsType], 2, len([srcIsType])-2) else [srcIsType] end)
      ,[srcAccessions]=(case when [srcAccessions] like char(34)+'%'+char(34) then substring([srcAccessions], 2, len([srcAccessions])-2) else [srcAccessions] end)
      ,[realm]=(case when [realm] like char(34)+'%'+char(34) then substring([realm], 2, len([realm])-2) else [realm] end)
      ,[subrealm]=(case when [subrealm] like char(34)+'%'+char(34) then substring([subrealm], 2, len([subrealm])-2) else [subrealm] end)
      ,[kingdom]=(case when [kingdom] like char(34)+'%'+char(34) then substring([kingdom], 2, len([kingdom])-2) else [kingdom] end)
      ,[subkingdom]=(case when [subkingdom] like char(34)+'%'+char(34) then substring([subkingdom], 2, len([subkingdom])-2) else [subkingdom] end)
      ,[phylum]=(case when [phylum] like char(34)+'%'+char(34) then substring([phylum], 2, len([phylum])-2) else [phylum] end)
      ,[subphylum]=(case when [subphylum] like char(34)+'%'+char(34) then substring([subphylum], 2, len([subphylum])-2) else [subphylum] end)
      ,[class]=(case when [class] like char(34)+'%'+char(34) then substring([class], 2, len([class])-2) else [class] end)
      ,[subclass]=(case when [subclass] like char(34)+'%'+char(34) then substring([subclass], 2, len([subclass])-2) else [subclass] end)
      ,[order]=(case when [order] like char(34)+'%'+char(34) then substring([order], 2, len([order])-2) else [order] end)
      ,[suborder]=(case when [suborder] like char(34)+'%'+char(34) then substring([suborder], 2, len([suborder])-2) else [suborder] end)
      ,[family]=(case when [family] like char(34)+'%'+char(34) then substring([family], 2, len([family])-2) else [family] end)
      ,[subfamily]=(case when [subfamily] like char(34)+'%'+char(34) then substring([subfamily], 2, len([subfamily])-2) else [subfamily] end)
      ,[genus]=(case when [genus] like char(34)+'%'+char(34) then substring([genus], 2, len([genus])-2) else [genus] end)
      ,[subgenus]=(case when [subgenus] like char(34)+'%'+char(34) then substring([subgenus], 2, len([subgenus])-2) else [subgenus] end)
      ,[species]=(case when [species] like char(34)+'%'+char(34) then substring([species], 2, len([species])-2) else [species] end)
      ,[isType]=(case when [isType] like char(34)+'%'+char(34) then substring([isType], 2, len([isType])-2) else [isType] end)
      ,[exemplarAccessions]=(case when [exemplarAccessions] like char(34)+'%'+char(34) then substring([exemplarAccessions], 2, len([exemplarAccessions])-2) else [exemplarAccessions] end)
      ,[exemplarName]=(case when [exemplarName] like char(34)+'%'+char(34) then substring([exemplarName], 2, len([exemplarName])-2) else [exemplarName] end)
      ,[exemplarRefSeq]=(case when [exemplarRefSeq] like char(34)+'%'+char(34) then substring([exemplarRefSeq], 2, len([exemplarRefSeq])-2) else [exemplarRefSeq] end)
      ,[exemplarIsolate]=(case when [exemplarIsolate] like char(34)+'%'+char(34) then substring([exemplarIsolate], 2, len([exemplarIsolate])-2) else [exemplarIsolate] end)
      ,[isComplete]=(case when [isComplete] like char(34)+'%'+char(34) then substring([isComplete], 2, len([isComplete])-2) else [isComplete] end)
      ,[Abbrev]=(case when [Abbrev] like char(34)+'%'+char(34) then substring([Abbrev], 2, len([Abbrev])-2) else [Abbrev] end)
      ,[change]=(case when [change] like char(34)+'%'+char(34) then substring([change], 2, len([change])-2) else [change] end)
      ,[rank]=(case when [rank] like char(34)+'%'+char(34) then substring([rank], 2, len([rank])-2) else [rank] end)
from  load_next_msl
where  
([proposal] is not null and ([proposal] like char(34)+'%'+char(34))) or  -- double quotes
([srcRealm] is not null and ([srcRealm] like char(34)+'%'+char(34))) or  -- double quotes
([srcSubrealm] is not null and ([srcSubrealm] like char(34)+'%'+char(34))) or  -- double quotes
([srcKingdom] is not null and ([srcKingdom] like char(34)+'%'+char(34))) or  -- double quotes
([srcSubkingdom] is not null and ([srcSubkingdom] like char(34)+'%'+char(34))) or  -- double quotes
([srcPhylum] is not null and ([srcPhylum] like char(34)+'%'+char(34))) or  -- double quotes
([srcSubphylum] is not null and ([srcSubphylum] like char(34)+'%'+char(34))) or  -- double quotes
([srcClass] is not null and ([srcClass] like char(34)+'%'+char(34))) or  -- double quotes
([srcSubclass] is not null and ([srcSubclass] like char(34)+'%'+char(34))) or  -- double quotes
([srcOrder] is not null and ([srcOrder] like char(34)+'%'+char(34))) or  -- double quotes
([srcSuborder] is not null and ([srcSuborder] like char(34)+'%'+char(34))) or  -- double quotes
([srcFamily] is not null and ([srcFamily] like char(34)+'%'+char(34))) or  -- double quotes
([srcSubfamily] is not null and ([srcSubfamily] like char(34)+'%'+char(34))) or  -- double quotes
([srcGenus] is not null and ([srcGenus] like char(34)+'%'+char(34))) or  -- double quotes
([srcSubgenus] is not null and ([srcSubgenus] like char(34)+'%'+char(34))) or  -- double quotes
([srcSpecies] is not null and ([srcSpecies] like char(34)+'%'+char(34))) or  -- double quotes
([srcIsType] is not null and ([srcIsType] like char(34)+'%'+char(34))) or  -- double quotes
([srcAccessions] is not null and ([srcAccessions] like char(34)+'%'+char(34))) or  -- double quotes
([realm] is not null and ([realm] like char(34)+'%'+char(34))) or  -- double quotes
([subrealm] is not null and ([subrealm] like char(34)+'%'+char(34))) or  -- double quotes
([kingdom] is not null and ([kingdom] like char(34)+'%'+char(34))) or  -- double quotes
([subkingdom] is not null and ([subkingdom] like char(34)+'%'+char(34))) or  -- double quotes
([phylum] is not null and ([phylum] like char(34)+'%'+char(34))) or  -- double quotes
([subphylum] is not null and ([subphylum] like char(34)+'%'+char(34))) or  -- double quotes
([class] is not null and ([class] like char(34)+'%'+char(34))) or  -- double quotes
([subclass] is not null and ([subclass] like char(34)+'%'+char(34))) or  -- double quotes
([order] is not null and ([order] like char(34)+'%'+char(34))) or  -- double quotes
([suborder] is not null and ([suborder] like char(34)+'%'+char(34))) or  -- double quotes
([family] is not null and ([family] like char(34)+'%'+char(34))) or  -- double quotes
([subfamily] is not null and ([subfamily] like char(34)+'%'+char(34))) or  -- double quotes
([genus] is not null and ([genus] like char(34)+'%'+char(34))) or  -- double quotes
([subgenus] is not null and ([subgenus] like char(34)+'%'+char(34))) or  -- double quotes
([species] is not null and ([species] like char(34)+'%'+char(34))) or  -- double quotes
([isType] is not null and ([isType] like char(34)+'%'+char(34))) or  -- double quotes
([exemplarAccessions] is not null and ([exemplarAccessions] like char(34)+'%'+char(34))) or  -- double quotes
([exemplarName] is not null and ([exemplarName] like char(34)+'%'+char(34))) or  -- double quotes
([exemplarRefSeq] is not null and ([exemplarRefSeq] like char(34)+'%'+char(34))) or  -- double quotes
([exemplarIsolate] is not null and ([exemplarIsolate] like char(34)+'%'+char(34))) or  -- double quotes
([isComplete] is not null and ([isComplete] like char(34)+'%'+char(34))) or  -- double quotes
([Abbrev] is not null and ([Abbrev] like char(34)+'%'+char(34))) or  -- double quotes
([change] is not null and ([change] like char(34)+'%'+char(34))) or  -- double quotes
([rank] is not null and ([rank] like char(34)+'%'+char(34)))   -- double quotes


--print ascii('"')
print '-- null proposals are bad'
select ERROR='NULL proposal field', *
from load_next_msl
where proposal is NULL

print '-- get correct suffixes on proposal names'
update load_next_msl set 
-- select count(*), proposal , 
	proposal=proposal+'.zip'
from load_next_msl 
where  proposal not like '%.___' and proposal not like '%.___x'
--group by proposal  -- for select summary

update load_next_msl set 
-- select ERROR='stripping .zip suffix', proposal , 
	proposal=left(proposal, len(proposal)-4)
from load_next_msl 
where  proposal  like '%.pdf.zip' or proposal  like '%.doc.zip' or proposal  like '%.docx.zip'

print '-- !!! YOU MUST COMMIT TRANSACTION - by default, leaves TX OPEN !!!! --'
print '-- COMMIT TRANSACTION '
--COMMIT TRANSACTION
--ROLLBACK TRANSACTION