USE [master]
GO


CREATE DATABASE [ICTVonline37]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ictv3_Data', FILENAME = N'D:\MSSQL\Data\ICTVonline37.mdf' , SIZE = 315008KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
 LOG ON 
( NAME = N'ictv3_Log', FILENAME = N'D:\MSSQL\Data\ICTVonline37_log.ldf' , SIZE = 2423872KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
GO

ALTER DATABASE [ICTVonline37] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ICTVonline37].[dbo].[sp_fulltext_database] @action = 'disable'
end
GO

ALTER DATABASE [ICTVonline37] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ICTVonline37] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ICTVonline37] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ICTVonline37] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ICTVonline37] SET ARITHABORT OFF 
GO

ALTER DATABASE [ICTVonline37] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ICTVonline37] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ICTVonline37] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ICTVonline37] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ICTVonline37] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ICTVonline37] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ICTVonline37] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ICTVonline37] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ICTVonline37] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ICTVonline37] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ICTVonline37] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ICTVonline37] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ICTVonline37] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ICTVonline37] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ICTVonline37] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ICTVonline37] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ICTVonline37] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ICTVonline37] SET RECOVERY BULK_LOGGED 
GO

ALTER DATABASE [ICTVonline37] SET  MULTI_USER 
GO

ALTER DATABASE [ICTVonline37] SET PAGE_VERIFY TORN_PAGE_DETECTION  
GO

ALTER DATABASE [ICTVonline37] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ICTVonline37] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ICTVonline37] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [ICTVonline37] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ICTVonline37] SET QUERY_STORE = OFF
GO

ALTER DATABASE [ICTVonline37] SET  READ_WRITE 
GO

