SET foreign_key_checks = 0;
DROP TABLE IF EXISTS `species_isolates`;
DROP TABLE IF EXISTS `taxonomy_change_in`;
DROP TABLE IF EXISTS `taxonomy_change_out`;
DROP TABLE IF EXISTS `taxonomy_genome_coverage`;
DROP TABLE IF EXISTS `taxonomy_host_source`;
--DROP TABLE IF EXISTS `taxonomy_json`;
--DROP TABLE IF EXISTS `taxonomy_json_rank`; 
DROP TABLE IF EXISTS `taxonomy_level`;
DROP TABLE IF EXISTS `taxonomy_molecule`;
DROP TABLE IF EXISTS `taxonomy_node`;
-- DROP TABLE IF EXISTS `taxonomy_node_delta`;
DROP TABLE IF EXISTS `taxonomy_node_merge_split`;
DROP TABLE IF EXISTS `taxonomy_toc`;
-- DROP TABLE IF EXISTS `virus_prop`;
SET foreign_key_checks = 1;
